server:
  port: 8083
spring:
  config:
    import: configserver:http://localhost:8082/
  application:
    name: "product"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  profiles:
    active: "default"
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/
  instance:
    prefer-ip-address: true
info:
  name: "product"
  description: "product services pour la gestion de product and categroy"
  version : 1.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true