services:
  product:
    image: mysql
    container_name: productdb
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE : product
  customers:
    image: mysql
    container_name: customers
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customers
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15673
